name: conda-environment
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.36.1
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - cmake=3.21.3
  - expat=2.4.1
  - gcc=10.3.0
  - gcc_impl_linux-64=10.3.0
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - libcurl=7.79.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=10.3.0
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.43.0
  - libsanitizer=10.3.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuv=1.42.0
  - lz4-c=1.9.3
  - ncurses=6.2
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - python_abi=3.9
  - readline=8.1
  - rhash=1.4.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - sysroot_linux-64=2.12
  - tk=8.6.11
  - tzdata=2021a
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
